services:
  - type: web
    name: remove_bg
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn remove_bg:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
